### PR TITLE
OSC Receivers for Mask and pattern

### PR DESCRIPTION
**Pull request by reno-**
and Fix aux feedback

### CODE REVIEW

**Comment by SteffeyDev** [comment]
Thanks for the work, the code looks good! What kind of testing have you done already?

**Comment by reno-** [comment]
I’ve worked for 2 weeks with it, no problems !

**Comment by reno-** [comment]
I tried to implement feedback for fly and pattern, but as long as my skills are limited to copy/paste code… there is something I missed, and I can’t managed to get it working.
https://github.com/PixelStereo/atemOSC/tree/feature/feedback-fly

**Comment by SteffeyDev** [comment]
Good to hear! That's merged, I'll take a look at the fly and pattern feedback and see if I can spot an issue.

**Comment by SteffeyDev** [comment]
We can discuss the flying key feedback in #254

**Comment by SteffeyDev** [comment]
Just FYI, this is what I meant by using a dictionary: https://github.com/SteffeyDev/atemOSC/commit/bc7c56ea3b7caf868833cbf2f1c5e20c9a0ac873

Now you can copy-paste that if needed in the future :)

**Comment by reno-** [comment]
> Just FYI, this is what I meant by using a dictionary: [bc7c56e](https://github.com/SteffeyDev/atemOSC/commit/bc7c56ea3b7caf868833cbf2f1c5e20c9a0ac873)
> 
> Now you can copy-paste that if needed in the future :)

Yes, thank you !

**Pull request merged**
